name: genomics-dashboard
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - streamlit
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - ete3
  - scikit-bio
  - biopython
  - mafft
  - clustalo
  - fasttree
  - iqtree2
